### ISSUE TITLE
Version contraints of dependencies cause unintended use of next major version of SQLAlchemy

### ISSUE THREAD

**Issue by stefanhettich** [pallets-eco/flask-sqlalchemy#1158]
**Environment**:
- Python version: 3.10
- Flask-SQLAlchemy version: 2.5.1
- SQLAlchemy version: 2.0.0 (which was not intended)

**Error**:
```
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    db = SQLAlchemy()
  File ".python-env/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 758, in __init__
    _include_sqlalchemy(self, query_class)
  File ".python-env/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 112, in _include_sqlalchemy
    for key in module.__all__:
AttributeError: module 'sqlalchemy' has no attribute '__all__'. Did you mean: '__file__'?
```

**Reason**:
The used version constraints for SQLAlchemy here in [`setup.py`](https://github.com/pallets-eco/flask-sqlalchemy/blob/2.x/setup.py#L31): `>=0.8.0` causes problems:

The new major version of SQLAlchemy (2.0.0) was released on January 26th 2023 ([Changelog](https://docs.sqlalchemy.org/en/20/changelog/changelog_20.html#change-2.0.0)) which for sure includes several breaking changes.
Due to the used version constraint for SQLAlchemy the newly available version of SQLAlchemy is used after a (re)install of the dependency Flask-SQLAlchemy (for example in CI/CD pipelines).

**Suggestion**:
I would suggest to set the version constraint to `^0.8.0` (if this syntax works for `pyproject.toml`).
The new 3.x version of Flask-SQLAlchemy might have the same problem, as the version contraint for SQLAlchemy is set ot `1.4.18`. But it might already support SQLAlchemy 2.x.

My current workaround (which maybe should be anyway to not rely on version management of dependencies) is to also set the version of SQLAlchemy in my project `requirements.txt`.

**Comment by davidism** [comment]
There is nothing in Flask-SQLAlchemy that is incompatible with SQLAlchemy 2.0. If _you_ have a dependency on SQLAlchemy<2, that's something _you_ need to pin.

Please read https://hynek.me/articles/semver-will-not-save-you/ or watch https://www.youtube.com/watch?v=WSVFw-3ssXM&t. When writing an application, you must use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Comment by davidism** [comment]
You are using an unsupported version of Flask-SQLAlchemy, please update to the latest version if possible. Please read https://hynek.me/articles/semver-will-not-save-you/ or watch https://www.youtube.com/watch?v=WSVFw-3ssXM&t. When writing an application, you must use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.
