### ISSUE TITLE
Add `db.transaction` block

### ISSUE THREAD

**Issue by immunda** [pallets-eco/flask-sqlalchemy#217]
Safely commits if no errors, will rollback otherwise.

**Comment by davidism** [comment]
Both SQLAlchemy and this extension have changed significantly since this was created. I am not convinced that Flask-SQLAlchemy needs to do anything special here, SQLAlchemy's transaction support should work. Also, this autocommit behavior seems related to the commit-on-teardown feature that is being removed.
